### ISSUE TITLE
Does not work under MacOS 10.15 Catalina

### ISSUE THREAD

**Issue by NBEGnHsx** [macyarounanoka/mac-zip-windows#1]
Fatal error: Uncaught Error: Class 'ZipArchive' not found in /Users/***/windowszip:128
Stack trace:
#0 /Users/***/Applications/windowszip(150): WindowsZip->Create('/Volumes/Data/D...')
#1 {main}
  thrown in /Users/***/windowszip on line 128

**Comment by kurudrive** [comment]
Me too  (´；ω；｀)

**Comment by KazuhiroM** [comment]
$ brew update
$ brew install php@7.3
$ brew link --force php@7.3

chenge windowszip
#!/usr/bin/php -> #!/usr/local/bin/pip

then it work.

**Comment by NBEGnHsx** [comment]
Thank you.
Worked that way.

**Comment by kurudrive** [comment]
1. open windowszip
2. change line 1
#!/usr/local/bin/php

I also succeeded.
Thank you.
